### ISSUE TITLE
this package isnt package for detect mock location but this dependency detect is aplication type is mock location

### ISSUE THREAD

**Issue by bagusandrewijaya** [zeexan-dev/detect_fake_location#1]

**Comment by zeexan-dev** [comment]
Thank you for your comment. The package includes functionality to detect whether mock location is enabled on Android and whether the location provided by the device is simulated or produced by an accessory on iOS. This can be seen as a way to indirectly determine if the application is utilizing fake location features. I hope this clarifies the purpose of the package.
