### ISSUE TITLE
Build failed with an exception

### ISSUE THREAD

**Issue by haftomlegese** [zeexan-dev/detect_fake_location#5]
![image](https://github.com/user-attachments/assets/cbfefdca-cd66-4923-87b0-4c7e6c8e4d31)

**Comment by zeexan-dev** [comment]
@haftomlegese Hi. I tested it with Flutter 3.24.3, it works fine. Which flutter version are you using?

**Comment by zeexan-dev** [comment]
@haftomlegese package updated. you can check. Thanks for reporing
